# Generated by Django 5.0.3 on 2024-04-01 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_event_attendees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="attendees",
        ),
    ]
